In [1]:
import pandas as pd
url = '/content/DataEngineeringQ2.json'
df = pd.read_json(url)
print(df)

         _id appointmentId                                     patientDetails  \
0   T6hf3rb5     40d2-9c9f  {'_id': 'T6hb630b3', 'firstName': 'Css', 'last...
1   T65g3rb5      40dbtc9f  {'_id': 'T6h33b300', 'firstName': 'Lokesh', 'l...
2   T7g6Srb5      g3Wt5c9f  {'_id': 'TjhB4373', 'phrId': '63b5hvy614d5', '...
3   94bg8W8d      fb6-a535  {'_id': '6df4R5b', 'phrId': '644nig7y', 'first...
4   T6h8H56c       67h7KL9  {'_id': 'lK9hy06a', 'firstName': 'Raghu Viju',...
5    T9Jh8c8        Hy7Y91  {'_id': 'kI9d5c6', 'firstName': 'Dinesh Kumar'...
6   9Is624b9     10dY8a-4a  {'_id': 'i9R324b7', 'phrId': '67Yt2b97', 'firs...
7   T8H9c3c6      e8056Ye8  {'_id': 'T6h41b5ad3d8002ad9c3c4', 'firstName':...
8    T8Ud380     dbc0-c66b  {'_id': 'T9Iy347e', 'firstName': 'Dinesh', 'la...
9    T345fG4        1576a7  {'_id': 'T4Rb1a2', 'firstName': 'Sanjay', 'las...
10  T4F6a175       b6Te4ac  {'_id': 'Tr4T2173', 'phrId': '6E48U79', 'first...
11   TW3r002        bu5Qfb  {'_id': 'T6Wa50', 'firstName': 'Nirmala', 'las...
12   6U6Ra36       86U8Y45  {'_id': '65sRa36', 'firstName': 'Satish', 'las...
13   u7Y7Aa5       Ufd7231  {'_id': 'UG67231', 'phrId': 'T6a7231', 'firstN...
14   T3R5dec       E4u5Ea2  {'_id': 'E4u5Ea2', 'firstName': 'Satyanaaryan'...
15   T4E7Ge6      T4E3e410  {'_id': 'T4E7Ge6', 'firstName': 'Nivitha', 'la...
16  E5336545       04Re22d  {'_id': '04Re22d', 'firstName': 'Tejpal', 'las...
17   T7Ys58b      af9784hf  {'_id': 'u7dWa589', 'firstName': 'Nandhini', '...
18  Y874Us5w       I8eW201  {'_id': 'TU7e913', 'firstName': 'Dhanamma', 'l...
19   Y7s5G42     f7r501cb1  {'_id': 'H8s2d40', 'firstName': 'Kushal', 'las...
20  Y7eE5cd8    cf092c8t6c  {'_id': 'u9cd6', 'phrId': '6463U8s231', 'first...
21   I9984e8      O02n262e  {'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...
22  Tu78a783      5dfN9s41  {'_id': 'h02U8a781', 'firstName': 'Preethi', '...
23   U9D2w6c      cc86re0f  {'_id': 'T6h40a5ad3d8002ad9c06a', 'firstName':...
24  T6hY6sEe       bd99dU7  {'_id': 'Y7sHec', 'firstName': 'Naresh', 'last...
25    H7sT6c        bcWe50  {'_id': 'T6h408981ayf32b63bcfa', 'firstName': ...
26   8Utyd5b       7au8se3  {'_id': 'T6U67af9', 'firstName': 'Govardhan', ...
27  y87Ta5c7      432cT213  {'_id': 'R53Et5W', 'firstName': 'Rajeshwari', ...
28  Ub7S65b7      D3fFr42c  {'_id': 'dE3r$2b5', 'firstName': 'Santosh', 'l...
29   yD7s2d7       7uyT6Rs  {'_id': 'TI93Hd5', 'firstName': 'Tarachand', '...
30   I9Sb4e8        O02n2e  {'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...

       phoneNumber                                   consultationData
0      96686896670  {'adviceTemplates': [], 'advices': [], 'attach...
1       9496368916  {'adviceTemplates': [], 'advices': [], 'attach...
2       7787204833  {'adviceTemplates': [], 'advices': [], 'attach...
3       9376756879  {'adviceTemplates': [], 'advices': [], 'attach...
4       5267384241  {'adviceTemplates': [], 'advices': [], 'attach...
5    +919826374025  {'adviceTemplates': [], 'advices': [], 'attach...
6       7587265252  {'adviceTemplates': [], 'advices': [], 'attach...
7       5586958767  {'adviceTemplates': [], 'advices': [], 'attach...
8       9987602525  {'adviceTemplates': [], 'advices': [], 'attach...
9       9234354366  {'adviceTemplates': [], 'advices': [], 'attach...
10      4863281056  {'adviceTemplates': [], 'advices': [], 'attach...
11      8687986800  {'adviceTemplates': [], 'advices': [], 'attach...
12                  {'adviceTemplates': [], 'advices': [], 'attach...
13      7152684236  {'labTest': [], 'emrTemplates': [], 'doctorNot...
14                  {'adviceTemplates': [], 'advices': [], 'attach...
15      9184723620  {'adviceTemplates': [], 'advices': [], 'attach...
16                  {'adviceTemplates': [], 'advices': [], 'attach...
17      5847346075  {'adviceTemplates': [], 'advices': [], 'attach...
18      9064537237  {'adviceTemplates': [], 'advices': [], 'attach...
19                  {'adviceTemplates': [], 'advices': [], 'attach...
20       992727892  {'adviceTemplates': [], 'advices': [], 'attach...
21      6888324121  {'adviceTemplates': [], 'advices': [], 'attach...
22      8248594521  {'adviceTemplates': [], 'advices': [], 'attach...
23   +917938475936  {'adviceTemplates': [], 'advices': [], 'attach...
24  +9124648979746  {'adviceTemplates': [], 'advices': [], 'attach...
25   +916883788633  {'adviceTemplates': [], 'advices': [], 'attach...
26   +916636278363  {'adviceTemplates': [], 'advices': [], 'attach...
27      6525356535  {'adviceTemplates': [], 'advices': [], 'attach...
28                  {'adviceTemplates': [], 'advices': [], 'attach...
29   +919093872282  {'adviceTemplates': [], 'advices': [], 'attach...
30   +916888324121  {'adviceTemplates': [], 'advices': [], 'attach...

In [10]:
df.head()

,_id,appointmentId,_id,firstName,lastName,DOB,gender,medicines,adviceTemplates,advices,age,num_medicines
0,T6hf3rb5,40d2-9c9f,T6hb630b3,Css,Smith,2010-01-01,Male,"[MedicineA, MedicineB]",[],[],14,2
1,T65g3rb5,40dbtc9f,T6h33b300,,Kumar,2005-01-01,Male,[MedicineC],[],[],19,1
2,T7g6Srb5,g3Wt5c9f,TjhB4373,John,Doe,1990-05-15,Female,[],[],[],34,0
3,T8Utyd5b,7au8se3,T8Utyd5b,Rajeshwari,Reddy,1985-03-22,Female,"[MedicineD, MedicineE, MedicineF]",[],[],39,3

In [11]:
#for null value find
df.isnull()

,_id,appointmentId,_id,firstName,lastName,DOB,gender,medicines,adviceTemplates,advices,age,num_medicines
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              4 non-null      object
 1   appointmentId    4 non-null      object
 2   _id              4 non-null      object
 3   firstName        4 non-null      object
 4   lastName         4 non-null      object
 5   DOB              4 non-null      datetime64[ns]
 6   gender           4 non-null      object
 7   medicines        4 non-null      object
 8   adviceTemplates  4 non-null      object
 9   advices          4 non-null      object
 10  age              4 non-null      int64
 11  num_medicines    4 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(9)
memory usage: 512.0+ bytes

In [14]:
df.isnull().sum()

_id                0
appointmentId      0
_id                0
firstName          0
lastName           0
DOB                0
gender             0
medicines          0
adviceTemplates    0
advices            0
age                0
num_medicines      0
dtype: int64

In [2]:
import pandas as pd
from pandas import json_normalize
data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': ''},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '1980-01-01'},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15'}
    ],
    'phoneNumber': ['96686896670', '9496368916', '7787204833'],
    'consultationData': [{'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}]
}

df = pd.DataFrame(data)
patient_details_df = json_normalize(df['patientDetails'])
df = pd.concat([df.drop(columns=['patientDetails']), patient_details_df], axis=1)


def missing_percentage(series):

    missing_count = series.isna() | (series == '')
    return round(missing_count.mean() * 100, 2)


columns_of_interest = ['firstName', 'lastName', 'DOB']
missing_percentages = {col: missing_percentage(df[col]) for col in columns_of_interest}

print(missing_percentages)

{'firstName': 33.33, 'lastName': 0.0, 'DOB': 33.33}

In [3]:


data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': '', 'gender': 'Male'},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '1980-01-01', 'gender': ''},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15', 'gender': 'Female'},
        {'_id': 'T8Utyd5b', 'firstName': 'Rajeshwari', 'lastName': 'Reddy', 'DOB': '1985-03-22', 'gender': ''}
    ],
    'phoneNumber': ['96686896670', '9496368916', '7787204833', '6525356535'],
    'consultationData': [{'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}]
}

df = pd.DataFrame(data)
patient_details_df = pd.json_normalize(df['patientDetails'])
df = pd.concat([df.drop(columns=['patientDetails']), patient_details_df], axis=1)
mode_gender = df['gender'].mode()[0]

df['gender'] = df['gender'].replace('', mode_gender).fillna(mode_gender)

female_percentage = (df['gender'] == 'Female').mean() * 100

print(f"Percentage of female gender after imputation: {female_percentage:.2f}%")

Percentage of female gender after imputation: 25.00%

In [4]:

data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': '2010-01-01', 'gender': 'Male'},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '2005-01-01', 'gender': 'Male'},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15', 'gender': 'Female'},
        {'_id': 'T8Utyd5b', 'firstName': 'Rajeshwari', 'lastName': 'Reddy', 'DOB': '1985-03-22', 'gender': 'Female'}
    ],
    'phoneNumber': ['96686896670', '9496368916', '7787204833', '6525356535'],
    'consultationData': [{'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}, {'adviceTemplates': [], 'advices': []}]
}

df = pd.DataFrame(data)


patient_details_df = pd.json_normalize(df['patientDetails'])
df = pd.concat([df.drop(columns=['patientDetails']), patient_details_df], axis=1)
df['DOB'] = pd.to_datetime(df['DOB'], errors='coerce')

today = pd.to_datetime('today')
df['age'] = (today - df['DOB']).dt.days // 365

def categorize_age(age):
    if pd.isna(age):
        return None
    if age <= 12:
        return 'Child'
    elif 13 <= age <= 19:
        return 'Teen'
    elif 20 <= age <= 59:
        return 'Adult'
    else:
        return 'Senior'

df['ageGroup'] = df['age'].apply(categorize_age)

adult_count = df['ageGroup'].value_counts().get('Adult', 0)

print(f"Count of Adult patients: {adult_count}")

Count of Adult patients: 2

In [5]:

data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': '2010-01-01', 'gender': 'Male'},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '2005-01-01', 'gender': 'Male'},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15', 'gender': 'Female'},
        {'_id': 'T8Utyd5b', 'firstName': 'Rajeshwari', 'lastName': 'Reddy', 'DOB': '1985-03-22', 'gender': 'Female'}
    ],
    'consultationData': [
        {'medicines': ['MedicineA', 'MedicineB'], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineC'], 'adviceTemplates': [], 'advices': []},
        {'medicines': [], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineD', 'MedicineE', 'MedicineF'], 'adviceTemplates': [], 'advices': []}
    ]
}

df = pd.DataFrame(data)
consultation_data_df = pd.json_normalize(df['consultationData'])
df = pd.concat([df.drop(columns=['consultationData']), consultation_data_df], axis=1)
df['num_medicines'] = df['medicines'].apply(lambda x: len(x) if isinstance(x, list) else 0)
average_medicines = df['num_medicines'].mean()

print(f"Average number of medicines prescribed: {average_medicines:.2f}")

Average number of medicines prescribed: 1.50

In [6]:
import pandas as pd
from collections import Counter
data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': '2010-01-01', 'gender': 'Male'},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '2005-01-01', 'gender': 'Male'},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15', 'gender': 'Female'},
        {'_id': 'T8Utyd5b', 'firstName': 'Rajeshwari', 'lastName': 'Reddy', 'DOB': '1985-03-22', 'gender': 'Female'}
    ],
    'consultationData': [
        {'medicines': ['MedicineA', 'MedicineB'], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineC'], 'adviceTemplates': [], 'advices': []},
        {'medicines': [], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineD', 'MedicineE', 'MedicineF'], 'adviceTemplates': [], 'advices': []}
    ]
}

df = pd.DataFrame(data)
consultation_data_df = pd.json_normalize(df['consultationData'])
df = pd.concat([df.drop(columns=['consultationData']), consultation_data_df], axis=1)
all_medicines = [medicine for sublist in df['medicines'] for medicine in sublist]
medicine_counts = Counter(all_medicines)
medicine_counts_df = pd.DataFrame(medicine_counts.items(), columns=['medicineName', 'count'])
medicine_counts_df = medicine_counts_df.sort_values(by='count', ascending=False)
if len(medicine_counts_df) >= 3:
    third_most_frequent_medicine = medicine_counts_df.iloc[2]['medicineName']
else:
    third_most_frequent_medicine = None

print(f"3rd most frequently prescribed medicine: {third_most_frequent_medicine}")

3rd most frequently prescribed medicine: MedicineC

In [7]:
data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'consultationData': [
        {'medicines': ['MedicineA', 'MedicineB'], 'status': ['Active', 'Inactive']},
        {'medicines': ['MedicineC'], 'status': ['Inactive']},
        {'medicines': [], 'status': []},
        {'medicines': ['MedicineD', 'MedicineE', 'MedicineF'], 'status': ['Active', 'Inactive', 'Inactive']}
    ]
}

df = pd.DataFrame(data)
consultation_data_df = pd.json_normalize(df['consultationData'])
df = pd.concat([df.drop(columns=['consultationData']), consultation_data_df], axis=1)
medicines_list = [medicine for sublist in df['medicines'] for medicine in sublist]
statuses_list = [status for sublist in df['status'] for status in sublist]
medicines_df = pd.DataFrame({
    'medicineName': medicines_list,
    'status': statuses_list
})

status_counts = medicines_df['status'].value_counts()
total_medicines = len(medicines_df)
active_percentage = (status_counts.get('Active', 0) / total_medicines) * 100
inactive_percentage = (status_counts.get('Inactive', 0) / total_medicines) * 100

print(f"Percentage of Active Medicines: {active_percentage:.2f}%")
print(f"Percentage of Inactive Medicines: {inactive_percentage:.2f}%")

Percentage of Active Medicines: 33.33%
Percentage of Inactive Medicines: 66.67%

In [8]:

data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'phoneNumber': ['+919876787687', '919877475896', '+913454768688', '9876787687']
}

df = pd.DataFrame(data)

def is_valid_phone_number(phone_number):

    if phone_number.startswith('+91'):
        phone_number = phone_number[3:]
    elif phone_number.startswith('91'):
        phone_number = phone_number[2:]


    if len(phone_number) == 10 and phone_number.isdigit():

        number = int(phone_number)
        return 6000000000 <= number <= 9999999999

    return False

df['isValidMobile'] = df['phoneNumber'].apply(is_valid_phone_number)

valid_phone_count = df['isValidMobile'].sum()

print(df)
print(f"Number of valid phone numbers: {valid_phone_count}")

        _id appointmentId    phoneNumber  isValidMobile
0  T6hf3rb5     40d2-9c9f  +919876787687           True
1  T65g3rb5      40dbtc9f   919877475896           True
2  T7g6Srb5      g3Wt5c9f  +913454768688          False
3  T8Utyd5b       7au8se3     9876787687           True
Number of valid phone numbers: 3

In [9]:

data = {
    '_id': ['T6hf3rb5', 'T65g3rb5', 'T7g6Srb5', 'T8Utyd5b'],
    'appointmentId': ['40d2-9c9f', '40dbtc9f', 'g3Wt5c9f', '7au8se3'],
    'patientDetails': [
        {'_id': 'T6hb630b3', 'firstName': 'Css', 'lastName': 'Smith', 'DOB': '2010-01-01', 'gender': 'Male'},
        {'_id': 'T6h33b300', 'firstName': '', 'lastName': 'Kumar', 'DOB': '2005-01-01', 'gender': 'Male'},
        {'_id': 'TjhB4373', 'firstName': 'John', 'lastName': 'Doe', 'DOB': '1990-05-15', 'gender': 'Female'},
        {'_id': 'T8Utyd5b', 'firstName': 'Rajeshwari', 'lastName': 'Reddy', 'DOB': '1985-03-22', 'gender': 'Female'}
    ],
    'consultationData': [
        {'medicines': ['MedicineA', 'MedicineB'], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineC'], 'adviceTemplates': [], 'advices': []},
        {'medicines': [], 'adviceTemplates': [], 'advices': []},
        {'medicines': ['MedicineD', 'MedicineE', 'MedicineF'], 'adviceTemplates': [], 'advices': []}
    ]
}

df = pd.DataFrame(data)
patient_details_df = pd.json_normalize(df['patientDetails'])
consultation_data_df = pd.json_normalize(df['consultationData'])


df = pd.concat([df.drop(columns=['patientDetails', 'consultationData']), patient_details_df, consultation_data_df], axis=1)

today = pd.to_datetime('today')
df['DOB'] = pd.to_datetime(df['DOB'])
df['age'] = (today - df['DOB']).dt.days // 365


df['num_medicines'] = df['medicines'].apply(lambda x: len(x) if isinstance(x, list) else 0)


correlation = df[['age', 'num_medicines']].corr().iloc[0, 1]

print(df)
print(f"Pearson correlation between number of prescribed medicines and age: {correlation:.2f}")

        _id appointmentId        _id   firstName lastName        DOB  gender  \
0  T6hf3rb5     40d2-9c9f  T6hb630b3         Css    Smith 2010-01-01    Male
1  T65g3rb5      40dbtc9f  T6h33b300                Kumar 2005-01-01    Male
2  T7g6Srb5      g3Wt5c9f   TjhB4373        John      Doe 1990-05-15  Female
3  T8Utyd5b       7au8se3   T8Utyd5b  Rajeshwari    Reddy 1985-03-22  Female

                           medicines adviceTemplates advices  age  \
0             [MedicineA, MedicineB]              []      []   14
1                        [MedicineC]              []      []   19
2                                 []              []      []   34
3  [MedicineD, MedicineE, MedicineF]              []      []   39

   num_medicines
0              2
1              1
2              0
3              3
Pearson correlation between number of prescribed medicines and age: 0.11